modLoader="javafml"
loaderVersion="${forge_loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/crittscott/SomeStacks/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''
displayURL="https://github.com/crittscott/SomeStacks/tree/1.21.1"
logoFile="assets/somestacks/icon.png"

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
