plugins {
    id 'com.gradleup.shadow'
}

architectury {
    platformSetupLoomIde()
    forge()
}

sourceSets {
    gametest {
        java { srcDir project(':common').file('src/gametest/java') }
        compileClasspath += sourceSets.main.compileClasspath + sourceSets.main.output
        runtimeClasspath += sourceSets.main.runtimeClasspath + sourceSets.main.output +
                project(':common').sourceSets.main.output
    }
}

loom {
    mods {
        main {
            sourceSet sourceSets.main
            sourceSet project(':common').sourceSets.main
        }
        somestacks_gametest {
            sourceSet sourceSets.gametest
        }
    }

    runs {
        gameTestServer {
            server()
            environment 'gametestserver'
            forgeTemplate 'gameTestServer'
            name 'Game Test Server'
            property 'forge.enabledGameTestNamespaces', mod_id
            source sourceSets.gametest
        }
    }
}

rootProject.configureLoaderBuild(project)

dependencies {
    forge "net.minecraftforge:forge:$rootProject.forge_compile_version"

    common(project(path: ':common', configuration: 'namedElements')) { transitive = false }
    shadowBundle project(path: ':common', configuration: 'transformProductionForge')
}

tasks.named('processGametestResources', ProcessResources).configure {
    var replaceProperties = [
            forge_loader_version_range: forge_loader_version_range,
            mod_license: mod_license,
            mod_version: mod_version,
    ]
    inputs.properties replaceProperties

    filesMatching('META-INF/mods.toml') {
        expand replaceProperties + [project: project]
    }
}

// Expands ${...} placeholders in mods.toml (this module's own resource).
tasks.named('processResources', ProcessResources).configure {
    var replaceProperties = [
            minecraft_version: minecraft_version, minecraft_version_range: minecraft_version_range,
            forge_version_range: forge_version_range,
            forge_loader_version_range: forge_loader_version_range,
            mod_id: mod_id, mod_name: mod_name, mod_license: mod_license, mod_version: mod_version,
            mod_authors: mod_authors, mod_description: mod_description,
    ]
    inputs.properties replaceProperties

    filesMatching('META-INF/mods.toml') {
        expand replaceProperties + [project: project]
    }
}
